/* Filename: financial/generalledger/gl-data.js */
import { BarChart3 } from 'lucide-react';

export const GL_MENU = {
  id: 'gl',
  label: { en: 'General Ledger', fa: 'دفتر کل' },
  children: [
    {
      id: 'gl_settings',
      label: { en: 'GL Settings', fa: 'تنظیمات دفتر کل' },
      children: [
        { id: 'auto_num', label: { en: 'Auto Numbering', fa: 'شماره‌گذاری اتوماتیک' } },
        { id: 'year_end_setup', label: { en: 'Year-end Settings', fa: 'تنظیمات عملیات پایان سال' } },
        { id: 'allowed_modules', label: { en: 'Allowed Modules', fa: 'ماژول‌های مجاز' } },
      ]
    },
    {
      id: 'gl_base_info',
      label: { en: 'Base Information', fa: 'اطلاعات پایه' },
      children: [
        { id: 'ledgers', label: { en: 'Ledgers', fa: 'دفاتر' } },
        { id: 'acc_structure', label: { en: 'Account Structure', fa: 'ساختار حساب' } },
        { id: 'details', label: { en: 'Details', fa: 'تفصیل‌ها' } },
        { id: 'fiscal_periods', label: { en: 'Fiscal Periods', fa: 'دوره‌های مالی' } },
        { id: 'doc_types', label: { en: 'Document Types', fa: 'انواع اسناد' } },
        { id: 'std_desc', label: { en: 'Standard Descriptions', fa: 'شرح‌های استاندارد' } },
      ]
    },
    {
      id: 'gl_docs',
      label: { en: 'Document Management', fa: 'مدیریت اسناد' },
      children: [
        { id: 'doc_list', label: { en: 'Document List', fa: 'فهرست اسناد' } },
        { id: 'doc_review', label: { en: 'Document Review', fa: 'بررسی اسناد' } },
        { id: 'doc_finalize', label: { en: 'Finalize Documents', fa: 'قطعی کردن اسناد' } },
      ]
    },
    {
      id: 'gl_reports',
      label: { en: 'Reports & Analytics', fa: 'گزارش‌ها و تحلیل‌ها' },
      children: [
        { id: 'print_doc', label: { en: 'Print Accounting Doc', fa: 'چاپ سند حسابداری' } },
        { id: 'acc_review', label: { en: 'Account Review', fa: 'مرور حساب‌ها' } },
      ]
    }
  ]
};

export const GL_TRANS = {
  en: {
    // Buttons & Common
    btn_save: "Save",
    btn_cancel: "Cancel",
    btn_add: "Add",
    btn_close: "Close",
    edit: "Edit",
    delete: "Delete",
    active: "Active",
    inactive: "Inactive",
    filter: "Filter",
    active_status: "Status",
    alert_req_fields: "Please fill all required fields.",
    confirm_delete: "Are you sure you want to delete {0} items?",
    description: "Description",
    save_success: "Settings saved successfully.",

    // Document Management
    acc_mgmt_title: "Accounting Document Management",
    acc_mgmt_subtitle: "List of all financial documents with search and batch operation capabilities",
    grid_title: "Document List",
    col_docNo: "Doc No",
    col_date: "Date",
    col_dept: "Department",
    col_desc: "Description",
    col_debtor: "Debtor",
    col_status: "Status",
    col_active: "Active",
    col_actions: "Actions",
    status_final: "Final",
    status_draft: "Draft",
    status_reviewed: "Reviewed",
    filter_fromDoc: "From Doc No",
    filter_toDoc: "To Doc No",
    filter_fromDate: "From Date",
    filter_toDate: "To Date",
    filter_status: "Document Status",
    filter_costCenter: "Cost Center",
    filter_subsidiary: "Subsidiary Account",
    filter_allStatus: "All Statuses",
    modal_newDoc: "New Document",
    modal_editDoc: "Edit Document",
    modal_warning: "Note: Changes to final documents require financial manager approval.",
    field_docType: "Document Type",
    field_general: "General",
    field_opening: "Opening",
    field_party: "Party",
    field_selectParty: "Select Person...",
    field_amount: "Document Amount",
    field_isActive: "Active Document",

    // Ledgers Page
    ledgers_title: "Ledgers Management",
    ledgers_subtitle: "Define and manage organization ledgers and their configurations",
    lg_code: "Ledger Code",
    lg_title: "Ledger Title",
    lg_structure: "Account Structure",
    lg_currency: "Base Currency",
    lg_main: "Main Ledger",
    lg_main_desc: "Is this the main ledger?",
    lg_status: "Status",
    lg_new: "New Ledger",
    lg_edit: "Edit Ledger",
    lg_structure_ph: "Select Account Structure...",
    lg_currency_ph: "Select Currency...",

    // Details (Tafsils) Page
    details_title: "Detail Accounts",
    details_subtitle: "Manage detail types and their mapped codes",
    dt_type_title: "Detail Type Title",
    dt_category: "Category",
    dt_system: "System",
    dt_user: "User Defined",
    dt_new: "New Detail Type",
    dt_edit: "Edit Detail Type",
    dt_instances: "Detail Items",
    dt_view_instances: "View Items / Codes",
    dt_instance_list: "List of Items for: ",
    dt_entity_code: "Entity Code",
    dt_entity_title: "Entity Title",
    dt_alloc_code: "Allocated Detail Code",
    dt_assign_btn: "Assign Code",
    dt_assign_title: "Assign Detail Code",
    dt_enter_code: "Enter the new detail code for this entity:",

    // Fiscal Periods Page
    fp_title: "Fiscal Periods Management",
    fp_subtitle: "Define fiscal years and their operational periods",
    fp_year_code: "Year Code",
    fp_year_title: "Year Title",
    fp_start_date: "Start Date",
    fp_end_date: "End Date",
    fp_calendar_type: "Calendar System",
    fp_jalali: "Jalali (Persian)",
    fp_gregorian: "Gregorian",
    fp_new_year: "New Fiscal Year",
    fp_edit_year: "Edit Fiscal Year",
    fp_ops_periods: "Operational Periods",
    fp_period_code: "Period Code",
    fp_period_title: "Period Title",
    fp_status: "Period Status",
    fp_st_not_open: "Not Open",
    fp_st_open: "Open",
    fp_st_closed: "Closed",
    fp_auto_gen: "Auto Generate Periods",
    fp_gen_monthly: "Monthly",
    fp_gen_quarterly: "Quarterly",
    fp_gen_semi: "Semi-Annually",
    fp_exceptions: "Access Exceptions",
    fp_exc_desc: "Users allowed to bypass current period status",
    fp_add_user: "Add User to Exceptions",
    fp_user: "User",
    fp_select_user: "Select User...",
    
    // Document Types Page
    doctype_title: "Accounting Document Types",
    doctype_subtitle: "Manage system and user-defined document types for categorization",
    dt_doc_title: "Document Type Title",
    dt_sys_opening: "Opening",
    dt_sys_general: "General",
    dt_sys_closing: "Closing",
    dt_sys_close_acc: "Closing Accounts",
    dt_sys_adj_begin: "Beginning Year Adjustment",
    dt_sys_adj_end: "End Year Adjustment",
    dt_sys_rev_mon: "Monetary Item Revaluation",
    dt_sys_rev_rep: "Reporting Currency Revaluation",
    dt_sys_warehouse: "Warehouse",
    dt_sys_treasury: "Receipt & Payment",
    dt_sys_sales: "Sales",
    dt_sys_budget: "Budget",
    dt_manual_type: "User Defined",
    dt_auto_type: "System",
    dt_new_doc: "New Document Type",
    dt_edit_doc: "Edit Document Type",

    // Auto Numbering Page
    an_title: "Auto Numbering Settings",
    an_subtitle: "Configure numbering logic for Details, Accounts, and Documents",
    an_tab_details: "Detail Numbering",
    an_tab_accounts: "Account Numbering",
    an_tab_docs: "Document Numbering",
    
    // AN - Details
    an_dt_type: "Detail Type",
    an_dt_length: "Max Length",
    an_dt_start: "Start Code",
    an_dt_end: "End Code",
    an_dt_last: "Last Generated",
    an_edit_dt: "Edit Detail Numbering",
    
    // AN - Accounts
    an_acc_group: "Group Account",
    an_acc_general: "General Account",
    an_acc_subsidiary: "Subsidiary Account",
    an_mode: "Generation Mode",
    an_mode_auto: "Automatic",
    an_mode_manual: "Manual",
    an_acc_len: "Digit Length",
    
    // AN - Docs
    an_select_ledger: "Select Ledger",
    an_reset_year: "Reset Numbering on New Fiscal Year",
    an_unique_scope: "Uniqueness Control Scope",
    an_scope_none: "None",
    an_scope_ledger: "Ledger",
    an_scope_branch: "Branch",
    an_scope_company: "Company",

    // System Detail Names
    sys_partner: "Business Partner",
    sys_cost_center: "Cost Center",
    sys_project: "Project",
    sys_other_person: "Other Persons",
    sys_branch: "Branch",
    sys_bank_acc: "Bank Account",
    sys_cash: "Cash Fund",
    sys_petty: "Petty Cash",
    sys_customer_group: "Customer Group",
    sys_product_group: "Product Group",
    sys_sales_office: "Sales Office",
    sys_price_zone: "Pricing Zone",
    sys_item: "Item/Product",
  },
  fa: {
    // Buttons & Common
    btn_save: "ذخیره",
    btn_cancel: "انصراف",
    btn_add: "افزودن",
    btn_close: "بستن",
    edit: "ویرایش",
    delete: "حذف",
    active: "فعال",
    inactive: "غیرفعال",
    filter: "فیلتر",
    active_status: "وضعیت",
    alert_req_fields: "لطفاً تمام فیلدهای اجباری را پر کنید.",
    confirm_delete: "آیا از حذف {0} مورد اطمینان دارید؟",
    description: "توضیحات",
    save_success: "تنظیمات با موفقیت ذخیره شد.",

    // Document Management
    acc_mgmt_title: "مدیریت اسناد حسابداری",
    acc_mgmt_subtitle: "لیست کلیه اسناد مالی با قابلیت جستجو و عملیات گروهی",
    grid_title: "لیست اسناد",
    col_docNo: "شماره سند",
    col_date: "تاریخ",
    col_dept: "دپارتمان",
    col_desc: "شرح سند",
    col_debtor: "بدهکار (ریال)",
    col_status: "وضعیت",
    col_active: "فعال",
    col_actions: "عملیات",
    status_final: "نهایی",
    status_draft: "پیش‌نویس",
    status_reviewed: "بررسی شده",
    filter_fromDoc: "از شماره سند",
    filter_toDoc: "تا شماره سند",
    filter_fromDate: "از تاریخ",
    filter_toDate: "تا تاریخ",
    filter_status: "وضعیت سند",
    filter_costCenter: "مرکز هزینه",
    filter_subsidiary: "معین",
    filter_allStatus: "همه وضعیت‌ها",
    modal_newDoc: "سند جدید",
    modal_editDoc: "ویرایش سند",
    modal_warning: "لطفاً دقت کنید: تغییرات در اسناد نهایی نیازمند تایید مدیر مالی می‌باشد.",
    field_docType: "نوع سند",
    field_general: "عمومی",
    field_opening: "افتتاحیه",
    field_party: "طرف حساب",
    field_selectParty: "انتخاب شخص...",
    field_amount: "مبلغ سند",
    field_isActive: "سند فعال باشد",

    // Ledgers Page
    ledgers_title: "مدیریت دفاتر",
    ledgers_subtitle: "تعریف و مدیریت دفاتر کل سازمان و تنظیمات آنها",
    lg_code: "کد دفتر",
    lg_title: "عنوان دفتر",
    lg_structure: "ساختار حساب",
    lg_currency: "ارز اصلی",
    lg_main: "دفتر اصلی",
    lg_main_desc: "آیا این دفتر اصلی است؟",
    lg_status: "وضعیت",
    lg_new: "دفتر جدید",
    lg_edit: "ویرایش دفتر",
    lg_structure_ph: "انتخاب ساختار حساب...",
    lg_currency_ph: "انتخاب ارز...",

    // Details (Tafsils) Page
    details_title: "مدیریت تفصیل‌ها",
    details_subtitle: "مدیریت انواع تفصیل و کدهای تفصیلی تخصیص یافته به موجودیت‌ها",
    dt_type_title: "عنوان نوع تفصیل",
    dt_category: "نوع",
    dt_system: "سیستمی",
    dt_user: "کاربری (دستی)",
    dt_new: "تعریف تفصیل جدید",
    dt_edit: "ویرایش نوع تفصیل",
    dt_instances: "اقلام تفصیل",
    dt_view_instances: "مشاهده اقلام / کدها",
    dt_instance_list: "لیست اقلام مربوط به: ",
    dt_entity_code: "کد موجودیت",
    dt_entity_title: "عنوان موجودیت",
    dt_alloc_code: "کد تفصیلی تخصیص یافته",
    dt_assign_btn: "تخصیص کد",
    dt_assign_title: "تخصیص کد تفصیلی",
    dt_enter_code: "کد تفصیلی مورد نظر برای این موجودیت را وارد کنید:",

    // Fiscal Periods Page
    fp_title: "مدیریت دوره‌های مالی",
    fp_subtitle: "تعریف سال‌های مالی و دوره‌های عملیاتی زیرمجموعه",
    fp_year_code: "کد سال مالی",
    fp_year_title: "عنوان سال مالی",
    fp_start_date: "تاریخ شروع",
    fp_end_date: "تاریخ پایان",
    fp_calendar_type: "نوع تقویم",
    fp_jalali: "هجری شمسی",
    fp_gregorian: "میلادی",
    fp_new_year: "تعریف سال مالی جدید",
    fp_edit_year: "ویرایش سال مالی",
    fp_ops_periods: "دوره‌های عملیاتی",
    fp_period_code: "کد دوره",
    fp_period_title: "عنوان دوره",
    fp_status: "وضعیت دوره",
    fp_st_not_open: "باز نشده",
    fp_st_open: "باز",
    fp_st_closed: "بسته شده",
    fp_auto_gen: "تولید اتوماتیک دوره‌ها",
    fp_gen_monthly: "ماهانه",
    fp_gen_quarterly: "سه ماهه",
    fp_gen_semi: "شش ماهه",
    fp_exceptions: "استثنائات دسترسی",
    fp_exc_desc: "کاربرانی که مجاز به فعالیت در وضعیت فعلی دوره هستند",
    fp_add_user: "افزودن کاربر به لیست استثنا",
    fp_user: "نام کاربر",
    fp_select_user: "انتخاب کاربر...",
    
    // Document Types Page
    doctype_title: "انواع اسناد حسابداری",
    doctype_subtitle: "مدیریت انواع سندهای سیستمی و کاربری جهت دسته‌بندی اسناد",
    dt_doc_title: "عنوان نوع سند",
    dt_sys_opening: "افتتاحیه",
    dt_sys_general: "عمومی",
    dt_sys_closing: "اختتامیه",
    dt_sys_close_acc: "بستن حساب‌ها",
    dt_sys_adj_begin: "تعدیل ماهیت ابتدای سال",
    dt_sys_adj_end: "تعدیل ماهیت پایان سال",
    dt_sys_rev_mon: "تسعیر ارز اقلام پولی",
    dt_sys_rev_rep: "تسعیر به ارز گزارشگری",
    dt_sys_warehouse: "انبار",
    dt_sys_treasury: "دریافت و پرداخت",
    dt_sys_sales: "فروش",
    dt_sys_budget: "بودجه",
    dt_manual_type: "کاربری",
    dt_auto_type: "سیستمی",
    dt_new_doc: "تعریف نوع سند جدید",
    dt_edit_doc: "ویرایش نوع سند",

    // Auto Numbering Page
    an_title: "تنظیمات شماره‌گذاری اتوماتیک",
    an_subtitle: "پیکربندی منطق شماره‌گذاری برای تفصیل‌ها، حساب‌ها و اسناد",
    an_tab_details: "شماره‌گذاری تفصیل‌ها",
    an_tab_accounts: "شماره‌گذاری حساب‌ها",
    an_tab_docs: "شماره‌گذاری اسناد",
    
    // AN - Details
    an_dt_type: "نوع تفصیل",
    an_dt_length: "طول مجاز (رقم)",
    an_dt_start: "کد شروع",
    an_dt_end: "کد پایان",
    an_dt_last: "آخرین کد ایجاد شده",
    an_edit_dt: "ویرایش تنظیمات تفصیل",
    
    // AN - Accounts
    an_acc_group: "حساب گروه",
    an_acc_general: "حساب کل",
    an_acc_subsidiary: "حساب معین",
    an_mode: "نحوه تولید",
    an_mode_auto: "اتوماتیک",
    an_mode_manual: "دستی",
    an_acc_len: "تعداد ارقام",
    
    // AN - Docs
    an_select_ledger: "انتخاب دفتر کل",
    an_reset_year: "ریست شماره‌گذاری در سال مالی جدید",
    an_unique_scope: "محدوده کنترل یکتایی شماره سند",
    an_scope_none: "بدون کنترل",
    an_scope_ledger: "دفتر",
    an_scope_branch: "شعبه",
    an_scope_company: "شرکت",

    // System Detail Names
    sys_partner: "طرف تجاری",
    sys_cost_center: "مرکز هزینه",
    sys_project: "پروژه",
    sys_other_person: "سایر اشخاص حقیقی/حقوقی",
    sys_branch: "شعبه",
    sys_bank_acc: "حساب بانکی",
    sys_cash: "صندوق",
    sys_petty: "تنخواه",
    sys_customer_group: "گروه مشتری",
    sys_product_group: "گروه محصول",
    sys_sales_office: "دفتر فروش",
    sys_price_zone: "حوزه قیمت‌گذاری",
    sys_item: "کالا/محصول",
  }
};